### ISSUE TITLE
Is there any guide which shows how to duplicate this app behavior? 

### ISSUE THREAD

**Issue by jasan-s** [mcdonamp/sanichat#4]
Readme file mentioned that firebase Queue was used with a node server. I am unclear how to achieve this. THe node server contained in the backend folder was not hosted on Firebase right?

**Comment by eikooc** [comment]
No you have to host your own node.js server

**Comment by asciimike** [comment]
Yep, I host this on Google App Engine: https://cloud.google.com/appengine/docs/flexible/nodejs/
